apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - ./service-account.yaml
  - ./vault-auth.yaml
  - ./vault-connection.yaml
  - ./vault-static-secret.yaml
