apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-source
spec:
  vaultAuthRef: vault-auth-grafana
  mount: homelab
  type: kv-v2
  path: grafana/admin
  refreshAfter: 60s
  destination:
    name: grafana-admin-credentials
    create: true
