# values.yaml

grafana:
  admin:
    existingSecret: grafana-admin-credentials
    userKey: username
    passwordKey: password
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - grafana.olszewskib.org
    path: /
    pathType: Prefix
    tls:
      - hosts:
        - grafana.olszewskib.org
        secretName: grafana-tls


prometheus:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.olszewskib.org
    paths:
      - /
    pathType: Prefix

alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.olszewskib.org
    paths:
      - /
    pathType: Prefix
