# values.yaml

grafana:
  ingress:
    enabled: true
    hosts:
      - grafana.olszewskib.org
    path: /
    pathType: Prefix

prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.olszewskib.org
    paths:
      - /
    pathType: Prefix

alertmanager:
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.olszewskib.org
    paths:
      - /
    pathType: Prefix
